### ISSUE TITLE
ReactJS SDK

### ISSUE THREAD

**Issue by sz-dev** [episerver/content-delivery-js-sdk#36]
Is there any SDK for ReactJS
Can you share the if there is any sample or road map for it.

**Comment by DeepRed** [comment]
@sz-dev good question and something we have spoken about internally to some extent. Today we are not opinionated on different JS frameworks and we don't supply framework specific SDKs for the CMS. This sample repository is what we currently have to offer. If you want to request a React SDK to be made available please feel free to submit a request at https://feedback.optimizely.com/ so that our product managers can take a look at it.
I think the topic is interesting and maybe it is something that we should explore, but unfortunately we don't have anything to share currently.
